export default {
	INIT_PHOTOS_LIST : "INIT_PHOTOS_LIST",
	CHANGE_IMAGE_ANSWER :"CHANGE_IMAGE_ANSWER",
	PUT_NEW_IMAGE : "PUT_NEW_IMAGE",
	CLEAR_IMAGES_LIST_BEFORE:"CLEAR_IMAGES_LIST_BEFORE",
	INIT_PRODUCT_PHOTOANSWERS : "INIT_PRODUCT_PHOTOANSWERS",
	ADD_PRODUCT_PHOTOANSWERS : "ADD_PRODUCT_PHOTOANSWERS",
}