export default {
	START_LOAD :"START_LOAD",
	IMAGE_SELECT : "IMAGE_SELECT",
	MINUS_IMAGE :"MINUS_IMAGE",
	ADDSTOCKSTITLE :"ADDSTOCKSTITLE",
	ADDACTIONSTITLE : "ADDACTIONSTITLE",
	STOCKS_LOADET : "STOCKS_LOADET",
	ANSWERS_LOADET : "ANSWERS_LOADET",
	CLEAR_LOADING :"CLEAR_LOADING",
	DONEJOB : "DONEJOB",
	ADDPRODUCTSACTIONSTITLE:"ADDPRODUCTSACTIONSTITLE",
	ANSWERS_PROD_LOADET:"ANSWERS_PROD_LOADET"
}