export default {
	DELETE_ORDER_VIEW : "DELETE_ORDER_VIEW",
	UPDATE_STATUS_VIEW : "UPDATE_STATUS_VIEW",
	UPDATE_COMMENT_VIEW : "UPDATE_COMMENT_VIEW",
	INIT_ORDER_ORDERCOMPONENT : "INIT_ORDER_ORDERCOMPONENT",
}