
export default {
	INIT___WH :"INIT___WH",
	INIT___STOCKS:"INIT___STOCKS",
	ORDER_CHANGE_PAYFORM : "ORDER_CHANGE_PAYFORM",
	ORDER_CHANGE_DISCOUNT : "ORDER_CHANGE_DISCOUNT",
	ORDER_CHANGE_COMMMENT : "ORDER_CHANGE_COMMMENT",
	ORDER_CHANGE_DELIVERY : "ORDER_CHANGE_DELIVERY",
	SET_STOCKS_FOR_PR_FROM_ORDER : "SET_STOCKS_FOR_PR_FROM_ORDER",
	SET_ORDER_PRODUCT_QTY : "SET_ORDER_PRODUCT_QTY",
	SAVE_ORDERS_CHANGES : "SAVE_ORDERS_CHANGES",
	SAVE_STOCKS_CHANGES : "SAVE_STOCKS_CHANGES",
	ORDER_CLEAR_ORDER_DATA : "ORDER_CLEAR_ORDER_DATA",
	ORDER_CLEAR_STOCKS_DATA : "ORDER_CLEAR_STOCKS_DATA",
}