export default {
	INIT_STORE:"INIT_PRELOAD_LIST_STORE",
	LOAD_DATA_FINISHED:"PRELOAD_LOAD_DATA_FINISHED",
	RELOAD_DATA:"PRELOAD_RELOAD_DATA_AFTER_ERROR",
	CLEAR_STAGE:"PRELOAD_CLEAR_STAGEDATA"

};



