export default {
	PUT_NEW_ORDER : "PUT_NEW_ORDER",
	INIT_ORDERS_LIST_FROM_ROUTER : "INIT_ORDERS_LIST_FROM_ROUTER",
	INIT_PAYFORMS_ROUTER : "INIT_PAYFORMS_ROUTER",
	INIT_PRODUCTS_ROUTER : "INIT_PRODUCTS_ROUTER",
	INIT_TTPRICELIST_ROUTER : "INIT_TTPRICELIST_ROUTER",
	INIT_TTPRODUCTS_ROUTER : "INIT_TTPRODUCTS_ROUTER",
	INIT_STOCKS_ROUTER : "INIT_STOCKS_ROUTER",
	INIT_ORDER_ROUTER :"INIT_ORDER_ROUTER",
	INIT_WH_ROUTER :"INIT_WH_ROUTER",
}